[package]
name = "tui"
version = "0.1.0"
authors = ["Florian Dehau <work@fdehau.com>"]
description = """
A library to build rich user interfaces or dashboard for terminals
"""
keywords = ["tui", "terminal"]
repository = "https://github.com/fdehau/tui-rs"
license = "MIT"
exclude = ["docs", ".travis.yml"]

[dependencies]
termion = "1.1.1"
rustbox = "0.9.0"
bitflags = "0.7"
cassowary = "0.2.0"
log = "0.3"
unicode-segmentation = "0.1.2"
unicode-width = "0.1.3"

[dev-dependencies]
log4rs = "0.5.0"
rand = "0.3"
