[package]
name = "tui"
version = "0.1.1"
authors = ["Florian Dehau <work@fdehau.com>"]
description = """
A library to build rich terminal user interfaces or dashboards
"""
keywords = ["tui", "terminal", "dashboard"]
repository = "https://github.com/fdehau/tui-rs"
license = "MIT"
exclude = ["docs", ".travis.yml"]

[features]
default = ["rustbox", "termion"]

[dependencies]
bitflags = "0.7"
cassowary = "0.2.0"
log = "0.3"
unicode-segmentation = "0.1.2"
unicode-width = "0.1.3"
termion = { version = "1.1.1", optional = true }
rustbox = { version = "0.9.0", optional = true }

[dev-dependencies]
log4rs = "0.5.0"
rand = "0.3"
